export const Message = {
  ARE_YOU_SURE: "Are you sure",
  DELETE_ITEM: "Delete Item",
  CONFIRM_DELETE:
    "Are you sure you want to delete this item? This action is irreversible",
  UNABLE_TO_DELETE:
    "Unable to delete the last section. At least one section is required.",
  MISS_LAYOUT_TITLE: "Missing Layout Name",
  MISS_LAYOUT_DESC: "Please create a layout with a name first!",
  UPDATE_LAYOUT_TITLE: "Layout Updated",
  UPDATE_LAYOUT_DESC: "Your layout has been successfully updated.",
  UPDATE_FAIL_TITLE: "Update Failed",
  UPDATE_FAIL_DESC: "Something went wrong while updating the layout.",
  CREATE_LAYOUT_TITLE: "Layout Created",
  CREATE_LAYOUT_DESC: "Your layout has been successfully created.",
  CREATE_FAIL_TITLE: "Layout Creation Failed",
  CREATE_FAIL_DESC: "Unable to save layout. Please try again.",
  ERR_MSG_TITLE: "Unexpected Error",
  ERR_MSG_DESC: "An unexpected error has occurred. Please try again later.",
  DEL_LAYOUT_TITLE: "Layout Deleted",
  DEL_LAYOUT_DESC: "Your layout has been successfully deleted.",
  DEL_LAYOUT_FAIL_TITLE: "Unable to delete the layout.",
  DEL_LAYOUT_FAIL_DESC: "An unexpected error has occurred. Please try again.",
  OBJ_CREATE_TITLE: "New Object Created",
  OBJ_CREATE_DESC: "Object has been successfully created.",
  OBJ_UPDATE_TITLE: "Object Updated",
  OBJ_UPDATE_DESC: "Object has been successfully updated.",
  UPDATE_BUSRULE_TITLE: "Business Enforcement Rule Updated!",
  CREATE_BUSRULE_TITLE: "New Business Enforcement Rule Created!",
  UPDATE_ALERTRULE_TITLE: "Manage Alert Rule Updated!",
  CREATE_ALERTRULE_TITLE: "New Manage Alert Rule Created!",
  CREATE_RULE_DESC: " has been successfully created.",
  UPDATE_RULE_DESC: " has been successfully updated.",
  DEL_RULE_TITLE: "Rule Deleted",
  DEL_RULE_DESC: "Your rule has been successfully deleted.",
  UPDATE_COND_TITLE: "Manage Conditional Access Rule Updated!",
  CREATE_COND_TITLE: "New Manage Conditional Access Rule Created!",
};
